---
name: Iceberg Question
description: Questions around Apache PyIceberg
labels: ["kind:question"]
body:
  - type: markdown
    attributes:
      value: "Feel free to ask your question on [Slack](https://join.slack.com/t/apache-iceberg/shared_invite/zt-1znkcg5zm-7_FE~pcox347XwZE3GNfPg) as well."
  - type: textarea
    attributes:
      label: Question
      description: What is your question?
    validations:
      required: true
