---
name: Iceberg Bug report ðŸž
description: Problems, bugs and issues with Apache Iceberg
labels: ["kind:bug"]
body:
  - type: dropdown
    attributes:
      label: Apache Iceberg version
      description: What Apache Iceberg version are you using?
      multiple: false
      options:
        - "0.8.0 (latest release)"
        - "0.7.1"
        - "0.7.0"
        - "0.6.1"
        - "0.6.0"
        - "0.5.0"
        - "0.4.0"
        - "0.3.0"
        - "0.2.0"
        - "0.1.0"
        - "main (development)"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Please describe the bug ðŸž
      description: >
        Please describe the problem, what to expect, and how to reproduce.
        Feel free to include stacktraces and the Iceberg catalog configuration.
        You can include files by dragging and dropping them here.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Willingness to contribute
      description: The Apache Iceberg community encourages bug-fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the PyIceberg codebase?
      options:
        - label: I can contribute a fix for this bug independently
        - label: I would be willing to contribute a fix for this bug with guidance from the Iceberg community
        - label: I cannot contribute a fix for this bug at this time
