---
name: Iceberg Bug report 🐞
description: Problems, bugs and issues with Apache Iceberg
labels: ["kind:bug"]
body:
  - type: dropdown
    attributes:
      label: Apache Iceberg version
      description: What Apache Iceberg version are you using?
      multiple: false
      options:
        - "0.6.0 (latest release)"
        - "0.5.0"
        - "0.4.0"
        - "0.3.0"
        - "0.2.0"
        - "0.1.0"
        - "main (development)"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Please describe the bug 🐞
      description: >
        Please describe the problem, what to expect, and how to reproduce.
        Feel free to include stacktraces and the Iceberg catalog configuration.
        You can include files by dragging and dropping them here.
    validations:
      required: true
