---
name: Iceberg Improvement / Feature Request
description: New features with Apache PyIceberg
labels: ["kind:feature request"]
body:
  - type: textarea
    attributes:
      label: Feature Request / Improvement
      description: Please describe the feature and elaborate on the use case and motivation behind it
    validations:
      required: true
