#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

---
name: Iceberg Bug report ðŸž
description: Problems, bugs and issues with Apache Iceberg
labels: ["kind:bug"]
body:
  - type: dropdown
    attributes:
      label: Apache Iceberg version
      description: What Apache Iceberg version are you using?
      multiple: false
      options:
        - "0.9.1 (latest release)"
        - "0.9.0"
        - "0.8.1"
        - "0.8.0"
        - "0.7.1"
        - "0.7.0"
        - "0.6.1"
        - "0.6.0"
        - "0.5.0"
        - "0.4.0"
        - "0.3.0"
        - "0.2.0"
        - "0.1.0"
        - "main (development)"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Please describe the bug ðŸž
      description: >
        Please describe the problem, what to expect, and how to reproduce.
        Feel free to include stacktraces and the Iceberg catalog configuration.
        You can include files by dragging and dropping them here.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Willingness to contribute
      description: The Apache Iceberg community encourages bug-fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the PyIceberg codebase?
      options:
        - label: I can contribute a fix for this bug independently
        - label: I would be willing to contribute a fix for this bug with guidance from the Iceberg community
        - label: I cannot contribute a fix for this bug at this time
