# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""End-to-end integration tests for the pluggable execution backend.

These tests verify the FULL pipeline through the pluggable backend by:
1. Creating real Iceberg tables via Spark (through REST catalog + S3)
2. Generating positional AND equality delete files via Spark MoR mode
3. Reading back via pyiceberg's scan().to_arrow() and verifying correctness

This exercises the complete path:
    plan_files → orchestrate_scan → backends.compute.apply_positional_deletes
                                  → backends.compute.anti_join
                                  → backends.compute.filter
                                  → schema_reconciliation
                                  → to_arrow / to_arrow_batch_reader

Verifies end-to-end correctness with real Iceberg tables, positional delete files
generated by Spark, and the full pluggable backend pipeline.

Requirements:
    Docker services running via: docker compose -f dev/docker-compose-integration.yml up
    Provisioned via: python dev/provision.py

Run with:
    pytest tests/integration/test_execution_backends_e2e.py -m integration
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from pyiceberg.catalog.rest import RestCatalog
from pyiceberg.expressions import And, EqualTo, GreaterThan, GreaterThanOrEqual, LessThan

if TYPE_CHECKING:
    from pyspark.sql import SparkSession


@pytest.mark.integration
class TestPluggableBackendWithPositionalDeletes:
    """E2E: Tables provisioned by Spark with MoR positional deletes read correctly via pluggable backend.

    The test_positional_mor_deletes_v2 table is provisioned by dev/provision.py:
    - 12 rows: (dt, number=[1..12], letter=[a..l])
    - Row with number=9 (letter='i') is deleted via Spark MoR (positional delete)
    - Expected survivors: numbers [1,2,3,4,5,6,7,8,10,11,12]
    """

    def test_scan_to_arrow_with_positional_deletes(self, session_catalog: RestCatalog) -> None:
        """scan().to_arrow() correctly excludes positionally-deleted rows."""
        table = session_catalog.load_table("default.test_positional_mor_deletes_v2")

        # Verify delete files exist
        files = list(table.scan().plan_files())
        has_deletes = any(len(task.delete_files) > 0 for task in files)
        assert has_deletes, "Table should have position delete files from Spark MoR"

        # Full scan via pluggable backend
        result = table.scan().to_arrow()
        assert result.column("number").to_pylist() == [1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12]

    def test_scan_to_arrow_batch_reader_with_positional_deletes(self, session_catalog: RestCatalog) -> None:
        """scan().to_arrow_batch_reader() correctly excludes positionally-deleted rows."""
        table = session_catalog.load_table("default.test_positional_mor_deletes_v2")

        result = table.scan().to_arrow_batch_reader().read_all()
        assert result.column("number").to_pylist() == [1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12]

    def test_scan_with_filter_and_positional_deletes(self, session_catalog: RestCatalog) -> None:
        """Residual filter + positional deletes produce correct survivors."""
        table = session_catalog.load_table("default.test_positional_mor_deletes_v2")

        # Filter: letter >= 'e' AND letter < 'k'
        # Candidates: e(5), f(6), g(7), h(8), i(9), j(10)
        # After pos delete of number=9: [5, 6, 7, 8, 10]
        result = table.scan(row_filter=And(GreaterThanOrEqual("letter", "e"), LessThan("letter", "k"))).to_arrow()
        assert result.column("number").to_pylist() == [5, 6, 7, 8, 10]

    def test_scan_with_limit_and_positional_deletes(self, session_catalog: RestCatalog) -> None:
        """limit() correctly applies after positional delete resolution."""
        table = session_catalog.load_table("default.test_positional_mor_deletes_v2")

        result = table.scan(limit=3).to_arrow()
        assert result.column("number").to_pylist() == [1, 2, 3]

    def test_count_with_positional_deletes(self, session_catalog: RestCatalog) -> None:
        """count() returns correct value accounting for positional deletes."""
        table = session_catalog.load_table("default.test_positional_mor_deletes_v2")

        count = table.scan().count()
        assert count == 11  # 12 original - 1 deleted

    def test_double_positional_deletes(self, session_catalog: RestCatalog) -> None:
        """Two separate positional delete files applied to same data file."""
        table = session_catalog.load_table("default.test_positional_mor_double_deletes_v2")

        result = table.scan().to_arrow()
        # Rows 6 (f) and 9 (i) deleted
        assert result.column("number").to_pylist() == [1, 2, 3, 4, 5, 7, 8, 10, 11, 12]


@pytest.mark.integration
class TestPluggableBackendCowDeleteRoundTrip:
    """E2E: Create table, write, delete (CoW), verify via pluggable backend scan.

    This exercises the FULL write→delete→read pipeline:
    1. Create table via REST catalog
    2. Append data via pyiceberg
    3. Delete rows via pyiceberg CoW (which goes through pluggable backend)
    4. Read back via pluggable backend and verify
    """

    def test_cow_delete_and_scan_roundtrip(self, session_catalog: RestCatalog) -> None:
        """Full CoW delete cycle: write → delete → scan produces correct survivors."""
        import pyarrow as pa

        from pyiceberg.schema import Schema
        from pyiceberg.types import IntegerType, NestedField, StringType

        identifier = "default.__test_pluggable_cow_roundtrip"

        # Clean up from prior runs
        try:
            session_catalog.drop_table(identifier)
        except Exception:
            pass

        # Create table
        table = session_catalog.create_table(
            identifier,
            schema=Schema(
                NestedField(1, "id", IntegerType()),
                NestedField(2, "name", StringType()),
            ),
        )

        try:
            # Write 10 rows - explicitly use int32 to match IntegerType schema
            data = pa.table(
                {
                    "id": pa.array(list(range(1, 11)), type=pa.int32()),
                    "name": [f"row_{i}" for i in range(1, 11)],
                }
            )
            table.append(data)

            # Verify initial state
            assert table.scan().count() == 10

            # Delete rows where id > 7 (CoW rewrite)
            table.delete(GreaterThan("id", 7))

            # Scan via pluggable backend -- should show 7 rows
            result = table.scan().to_arrow()
            surviving_ids = sorted(result.column("id").to_pylist())
            assert surviving_ids == [1, 2, 3, 4, 5, 6, 7], f"After deleting id>7, expected [1..7], got {surviving_ids}"

            # Verify count
            assert table.scan().count() == 7

            # Verify batch reader path too
            batch_result = table.scan().to_arrow_batch_reader().read_all()
            assert sorted(batch_result.column("id").to_pylist()) == [1, 2, 3, 4, 5, 6, 7]

        finally:
            session_catalog.drop_table(identifier)

    def test_cow_delete_with_filter_roundtrip(self, session_catalog: RestCatalog) -> None:
        """CoW delete with equality filter, then scan with different filter."""
        import pyarrow as pa

        from pyiceberg.schema import Schema
        from pyiceberg.types import IntegerType, NestedField, StringType

        identifier = "default.__test_pluggable_cow_filter"

        try:
            session_catalog.drop_table(identifier)
        except Exception:
            pass

        table = session_catalog.create_table(
            identifier,
            schema=Schema(
                NestedField(1, "id", IntegerType()),
                NestedField(2, "category", StringType()),
            ),
        )

        try:
            # Explicitly use int32 to match IntegerType schema
            data = pa.table(
                {
                    "id": pa.array([1, 2, 3, 4, 5, 6], type=pa.int32()),
                    "category": ["a", "b", "a", "b", "a", "b"],
                }
            )
            table.append(data)

            # Delete all category='b' rows
            table.delete(EqualTo("category", "b"))

            # Scan all -- should show only category='a'
            result = table.scan().to_arrow()
            assert sorted(result.column("id").to_pylist()) == [1, 3, 5]
            assert all(c == "a" for c in result.column("category").to_pylist())

            # Scan with filter on surviving data
            result_filtered = table.scan(row_filter=GreaterThan("id", 2)).to_arrow()
            assert sorted(result_filtered.column("id").to_pylist()) == [3, 5]

        finally:
            session_catalog.drop_table(identifier)


@pytest.mark.integration
@pytest.mark.filterwarnings("ignore:Merge on read is not yet supported, falling back to copy-on-write")
class TestPluggableBackendWithSparkGeneratedDeletes:
    """E2E: Spark creates MoR deletes, pyiceberg reads them through pluggable backend.

    This test creates a fresh table, uses Spark to generate positional deletes,
    then verifies pyiceberg's pluggable backend correctly resolves them.
    """

    def test_spark_positional_delete_then_pyiceberg_scan(self, spark: SparkSession, session_catalog: RestCatalog) -> None:
        """Spark deletes rows, pyiceberg reads via pluggable backend.

        Note: Spark may use CoW or MoR depending on its optimization decisions.
        This test verifies that pyiceberg correctly reads the result regardless
        of the delete mechanism Spark chooses.
        """

        identifier = "default.__test_pluggable_spark_pos_del"

        spark.sql(f"DROP TABLE IF EXISTS rest.{identifier}")
        spark.sql(f"""
            CREATE TABLE rest.{identifier} (
                id INT,
                value STRING
            )
            USING iceberg
            TBLPROPERTIES (
                'format-version' = '2',
                'write.delete.mode' = 'merge-on-read',
                'write.update.mode' = 'merge-on-read',
                'write.merge.mode' = 'merge-on-read'
            )
        """)

        # Insert 5 rows
        spark.sql(f"""
            INSERT INTO rest.{identifier} VALUES
            (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')
        """)

        # Delete row where id=3 via Spark
        spark.sql(f"DELETE FROM rest.{identifier} WHERE id = 3")

        # Now read via pyiceberg pluggable backend
        table = session_catalog.load_table(identifier)

        # Check if delete files exist (informational - Spark may use CoW instead)
        tasks = list(table.scan().plan_files())
        has_deletes = any(len(t.delete_files) > 0 for t in tasks)
        if has_deletes:
            # MoR path: Spark generated positional deletes
            pass
        else:
            # CoW path: Spark rewrote the data files (also valid)
            pass

        # Read via pluggable backend - should work regardless of delete mechanism
        result = table.scan().to_arrow()
        surviving_ids = sorted(result.column("id").to_pylist())
        assert surviving_ids == [1, 2, 4, 5], f"Expected [1,2,4,5] after deleting id=3, got {surviving_ids}"

        # Count
        assert table.scan().count() == 4

        # Batch reader
        batch_result = table.scan().to_arrow_batch_reader().read_all()
        assert sorted(batch_result.column("id").to_pylist()) == [1, 2, 4, 5]

        # Cleanup
        spark.sql(f"DROP TABLE IF EXISTS rest.{identifier}")

    def test_spark_positional_delete_then_pyiceberg_cow_delete(self, spark: SparkSession, session_catalog: RestCatalog) -> None:
        """Spark creates pos delete, then pyiceberg does CoW delete on same file.

        This exercises the combined path: pos deletes from Spark + CoW rewrite from pyiceberg.
        The CoW rewrite must correctly account for the existing positional deletes.
        """

        identifier = "default.__test_pluggable_spark_cow_combo"

        spark.sql(f"DROP TABLE IF EXISTS rest.{identifier}")
        spark.sql(f"""
            CREATE TABLE rest.{identifier} (
                id INT,
                value STRING
            )
            USING iceberg
            TBLPROPERTIES (
                'format-version' = '2',
                'write.delete.mode' = 'merge-on-read'
            )
        """)

        spark.sql(f"""
            INSERT INTO rest.{identifier} VALUES
            (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')
        """)

        # Spark deletes id=2 (positional delete)
        spark.sql(f"DELETE FROM rest.{identifier} WHERE id = 2")

        # PyIceberg CoW deletes id=4 (rewrites file excluding pos-deleted AND CoW-deleted rows)
        table = session_catalog.load_table(identifier)
        table.delete(EqualTo("id", 4))

        # Reload table metadata after CoW
        table = session_catalog.load_table(identifier)
        result = table.scan().to_arrow()
        surviving_ids = sorted(result.column("id").to_pylist())

        # id=2 deleted by Spark (pos), id=4 deleted by pyiceberg (CoW)
        assert surviving_ids == [1, 3, 5], f"Expected [1,3,5], got {surviving_ids}"

        spark.sql(f"DROP TABLE IF EXISTS rest.{identifier}")
